In [1]:
import numpy as np
my_matrix=np.array([[1,2,7],[8,2,0],[6,3,1],[5,4,1],[9,0,1]])
print('my_matrix:\n',my_matrix)
print('Dimension of my_matrix:\n',my_matrix.ndim)
print('Shape of my_matrix:\n',my_matrix.shape)
print('Total row number of my_matrix:\n',my_matrix.shape[0])
print('Total column number of my_matrix:\n',my_matrix.shape[1])
print('Type of the elements in _matrix:\n',my_matrix.dtype.name)
print('Size in bytes of each element of my_matrix:\n',my_matrix.itemsize)
print('Total number of elements in my_matrix:\n',my_matrix.size)
my_matrix0 = my_matrix==1
print('Is there a 1 value in my_matrix?\n',my_matrix0.any()==True)
print('Where is value 1 in my_matrix?\n','row:',np.where(my_matrix0)[0],'\ncolumn:',np.where(my_matrix0)[1])
print('Transpose of my_matrix:n',my_matrix.T)
my_matrix_T = my_matrix.T
print('The first row of the transpose matrix:\n',my_matrix_T[0,:])
print('Sort the elementsn my_matrix with descending order:\n',-np.sort(-my_matrix,axis=None))


my_matrix:
 [[1 2 7]
 [8 2 0]
 [6 3 1]
 [5 4 1]
 [9 0 1]]
Dimension of my_matrix:
 2
Shape of my_matrix:
 (5, 3)
Total row number of my_matrix:
 5
Total column number of my_matrix:
 3
Type of the elements in _matrix:
 int32
Size in bytes of each element of my_matrix:
 4
Total number of elements in my_matrix:
 15
Is there a 1 value in my_matrix?
 True
Where is value 1 in my_matrix?
 row: [0 2 3 4] 
column: [0 2 2 2]
Transpose of my_matrix:n [[1 8 6 5 9]
 [2 2 3 4 0]
 [7 0 1 1 1]]
The first row of the transpose matrix:
 [1 8 6 5 9]
Sort the elementsn my_matrix with descending order:
 [9 8 7 6 5 4 3 2 2 1 1 1 1 0 0]


In [2]:
def my_intro(name,department,lab,country):
    print('My name is',name)
    print('I am from',department,',',lab)
    print('I came from',country)
    return 

name = "Lee Yi Shan"
department = 'Chemical Engineering Department'
lab = 'Computer Process System Engineering Lab'
country = 'Malaysia'

my_intro(name,department,lab,country)

My name is Lee Yi Shan
I am from Chemical Engineering Department , Computer Process System Engineering Lab
I came from Malaysia


In [3]:
import scipy.io as sio
my_array1 = my_matrix_T[0,:]
print(my_array1)
my_array2 = my_matrix_T[1,:]
print(my_array2)
my_array3 = my_matrix_T[2,:]
print(my_array3)
sio.savemat('my_array',{'row1':my_array1,'row2':my_array2,'row3':my_array3})

[1 8 6 5 9]
[2 2 3 4 0]
[7 0 1 1 1]


In [4]:
my_array = sio.loadmat('my_array')
print(my_array['row1'])
print(my_array['row2'])
print(my_array['row3'])


[[1 8 6 5 9]]
[[2 2 3 4 0]]
[[7 0 1 1 1]]
