# 1. Compound Data Types 
    簡便建立指定範圍數字之數列組合

In [16]:
import numpy as np               #使用型別為numpy中的ndarray
a = np.arange(2,20).reshape(6,3) #arange給定範圍 reshape給模式(幾組，幾個)   注意幾組乘上幾個須符合前面給定之範圍
print(a)
a = np.arange(2,30).reshape(4,7)
print(a)
print(type(a))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29]]
<class 'numpy.ndarray'>


# 2. User-Defined Functions
    產生第一題結果之function

In [27]:
import numpy as np
def numcombination(low,high,group) :
    if ( high - low ) % group == 0 :
        num = ( high - low ) / group
    else :
        print(str(high-low) + " cannot divide into " + str(group) + " groups" )
        return
    combination = np.arange(low,high).reshape(group,int(num))
    print(combination)
numcombination(1,10,3)
numcombination(1,10,4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 cannot divide into 4 groups


# 3. File I/O

In [43]:
f = open('input.txt','r')
print("filename:",f.name)
print("filemode:",f.mode)
print("file closed or not:",f.closed)
f.close()
print("file closed of not:",f.closed)

filename: input.txt
filemode: r
file closed or not: False
file closed of not: True
