 1. Compound Data Types
 numpy是學習資料科學的常見套件，Numpy的陣列就像是Python內建的list型態，但提供更有效率的儲存和操作。
 以下介紹numpy常見的三種函數zeros（）、ones（）、empty（）。

In [2]:
import numpy

In [3]:
import numpy as num

In [27]:
#zeros() ─ 創建二列四行的陣列,常用於賦予初始值
print( "num.zeros( (2,4) ): ")
print(num.zeros( (2,4) ))
print()

#ones() ─ 可創建任意維度和元素個數，且元素值均為1
print( "num.ones( (2,3,4), dtype = num.int16 ): ") #dtype:數據類型，可選參數，默認numpy.float64
print(num.ones( (2,3,4), dtype = num.int16 ) )
print()

#empty() ─ 元素值均為0
print( "num.empty( (2,2) ): ")
print(num.empty( (2,2) ) ) 

num.zeros( (2,4) ): 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

num.ones( (2,3,4), dtype = num.int16 ): 
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

num.empty( (2,2) ): 
[[0. 0.]
 [0. 0.]]


2. User-Defined Functions

In [41]:
def max(a, b): #定義名為max的函式
    return a if a > b else b
maximum = max # max 指向的函式指定給 maximum 變數
maximum(10, 20) # 傳回較大值

20

3. File I/O

In [69]:
#打開檔案 open(檔案名稱,模式) , 模式:r唯讀、w覆寫、a續寫
myfile = open ( "test.txt" , "r" ) 

#讀取檔案
#用size指定電腦自動讀取的字節數量,沒有設定就會讀取整個檔案
words= myfile.read(8)
print(words)

#關閉檔案
myfile.close()

    

Hello, m


In [73]:
#打開檔案
myfile2 = open('test2.txt', 'w')
#寫入檔案
myfile2.write("Hello, nice to meet you.")
#關閉檔案
myfile2.close()